apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: database
spec:
  selector:
    app: database-app
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: database
spec:
  selector:
    app: database-connect-app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    