apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  namespace: database
spec:
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
      - name: postgre
        image: postgres:latest
        resources:
          requests: 
            memory: "200Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "800m"
        ports:
        - containerPort: 5432
          name: postgre
        env: 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-admin-pass
              key: password 
        - name: POSTGRES_DB
          value: tempdb 
