apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wp-database
  template:
    metadata:
      labels:
        app: wp-database
    spec:
      volumes:
      - name: mysqldatastore
        persistentVolumeClaim: 
          claimName: mysql-datastore-vol1
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          requests: 
            memory: "200Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "800m"
        ports:
        - containerPort: 3306
          name: mysql
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-admin-pass
              key: password 
        - name: MYSQL_DATABASE
          value: wpdatabase
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-admin-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-admin-pass
              key: password
        volumeMounts:
        - name: mysqldatastore
          mountPath: /var/lib/mysql          


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      volumes:
      - name: wpdatastore
        persistentVolumeClaim: 
          claimName: wp-datastore-vol1
      containers:
      - name: wordpress
        image: wordpress:latest
        resources:
          requests: 
            memory: "200Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "800m"
        ports:
        - containerPort: 80
          name: mysql
        env: 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-admin-pass
              key: password 
        - name: WORDPRESS_DB_NAME
          value: wpdatabase
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-admin-pass
              key: username
        - name: WORDPRESS_DB_HOST
          value: mysql-svc.wordpress.svc.cluster.local       
        volumeMounts:
        - name: wpdatastore
          mountPath: /var/www/html/